export { default as NavBar } from './NavBar'
export { default as HomePage } from './HomePage'
export { default as Crypto } from './Crypto'
export { default as CryptoDetails } from './CryptoDetails'
export { default as News } from './News'